### ISSUE TITLE
Priority of \vdash

### ISSUE THREAD

**Issue by h0nzZik** [harp-project/AML-Formalization#108]
We should adjust the priorities of \vdash and matching logic connectives such that we can write
```
\Gamma \vdash a <---> b
```
instead of
```
\Gamma \vdash (a <---> b)
```

**Comment by h0nzZik** [comment]
`\vdash` should also bind tighter than propositional `/\`, so that we can write
```
\Gamma \vdash a /\ \Gamma \vdash b
```
instead of
```
(\Gamma \vdash a) /\ (\Gamma \vdash b)
```

**Comment by berpeti** [comment]
The precedence of all notations should be investigated. Also, the associativity should be sorted out.

**Comment by h0nzZik** [comment]
Notation "t $ r" has to be at level 65, because stdpp has it that way and we need to be compatible. It also defines
```
Infix "⊆" := subseteq (at level 70) : stdpp_scope.
```
which I would like to reuse for the subseteq pattern from `Definedness.v`. Similarly with
```
Infix "∈" := elem_of (at level 70) : stdpp_scope.
```
(see https://plv.mpi-sws.org/coqdoc/stdpp/stdpp.base.html)

Then the question is: what is the right priority of  `and`, `or`, `--->`, `<--->` with respect to these operations? One answer is: the same as for set union, intersection, etc. Another possible answer is:  the same as the standard library's `/\`, `\/`, `->`, `<->`.
Stdpp has:
```
Infix "∪" := union (at level 50, left associativity) : stdpp_scope.
Infix "∩" := intersection (at level 40) : stdpp_scope.
```

and the standard library has:
```
Reserved Notation "x -> y" (at level 99, right associativity, y at level 200).
Reserved Notation "x <-> y" (at level 95, no associativity).
Reserved Notation "x /\ y" (at level 80, right associativity).
Reserved Notation "x \/ y" (at level 85, right associativity).
Reserved Notation "~ x" (at level 75, right associativity).
```
(see https://coq.inria.fr/distrib/current/stdlib/Coq.Init.Notations.html)
. Which means:
* "or" is at higher level than "and" (we currently have that)
* "iff" is at higher level than "or" (we have that)
* implication is at higher level than "iff". We do not have that; currently, "--->" is at 90, and "iff" at 95. To fix this, I will make "--->" at 99.

**Comment by h0nzZik** [comment]
Actually, we want to be able to parse things like:
```
theory ⊢ phi1 ---> phi2 ->  theory ⊢ phi2
```.
Therefore, -> needs to have higher level than both \vdash and --->. We can make ---> at 96 and \vdash at 97.

**Comment by daniel-horpacsi** [comment]
I agree that the embedded logical symbols are supposed to bind tighter than the host logical symbols, but there's no silver bullet; optimize for the typical scenario (ML statements within Coq statements) and in some cases, users may need to use parentheses. As for the relative precedence of ML's connectives, I'd simply follow the standard.
