### ISSUE TITLE
Unification of `evar_quantify` and `free_evar_subst`

### ISSUE THREAD

**Issue by berpeti** [harp-project/AML-Formalization#146]

**Comment by berpeti** [comment]
Unfortunately, this is not possible, because `free_evar_subst` does not shift the variables in the pattern being substituted. With the capture-avoiding version, it could be possible though.

**Comment by h0nzZik** [comment]
@berpeti what is the status of this?

**Comment by berpeti** [comment]
It is still not plausible, unfortunately.
